language: erlang
otp_release:
  - 19.3
  - 18.3
  - 17.5
script:
  - make dialyzer
  - make xref
  - make
  - make test
notifications:
  email: christopher.meiklejohn@gmail.com
  email: tom@helium.com
sudo: false
